.\" vim:ts=4:sw=4:syntax=nroff
.fp 1 R
.fp 2 I
.fp 3 B
.fp 4 BI
.fp 5 CO
.fp 6 CI
.fp 7 CB
.nr X
.TH efmpath 1 "09 Nov 2009" "EFM Demo Tools"
.SH NAME
efmpath \- print EFM bin directory
.SH SYNOPSIS
\f3efmpath\f1 \f3-e\f1
.SH DESCRIPTION
.IX "efmpath"
.P
\f3efmpath\f1 returns the bin directory for the EFM product based on the
systemd(1) configuration.
The cluster in use is defined by the environment variable \f4$CLUSTER\f1
or the default "efm" if this is not present. 
.SH OPTIONS
.TP
\f3\-e\f1 
Insist that the unit file for EFM is in an enabled state.
.SH SEE ALSO
.BR systemd(1)
.SH NOTES
\f3efmpath\f1 returns the bin directory for the enabled systemd service for
EFM.
.P
If multiple services are enabled for the same cluster $CLUSTER then an error is returned.
.P
If no systemd service is enabled for EFM for this cluster and multiple versions of the product
are installed then the bin directory for the highest version number
of the installed services which is found is returned.
.SH AUTHOR
Simon Anthony (simon.anthony@hotmail.com)


